// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculate_solar_potential_cpp
NumericVector calculate_solar_potential_cpp(NumericMatrix coords, NumericMatrix normals, int year, int day_start, int day_end, int day_step, int minute_step, double min_sun_angle, double voxel_size, double lat, double lon, double timezone);
RcppExport SEXP _vostokR_calculate_solar_potential_cpp(SEXP coordsSEXP, SEXP normalsSEXP, SEXP yearSEXP, SEXP day_startSEXP, SEXP day_endSEXP, SEXP day_stepSEXP, SEXP minute_stepSEXP, SEXP min_sun_angleSEXP, SEXP voxel_sizeSEXP, SEXP latSEXP, SEXP lonSEXP, SEXP timezoneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< int >::type year(yearSEXP);
    Rcpp::traits::input_parameter< int >::type day_start(day_startSEXP);
    Rcpp::traits::input_parameter< int >::type day_end(day_endSEXP);
    Rcpp::traits::input_parameter< int >::type day_step(day_stepSEXP);
    Rcpp::traits::input_parameter< int >::type minute_step(minute_stepSEXP);
    Rcpp::traits::input_parameter< double >::type min_sun_angle(min_sun_angleSEXP);
    Rcpp::traits::input_parameter< double >::type voxel_size(voxel_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    Rcpp::traits::input_parameter< double >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< double >::type timezone(timezoneSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_solar_potential_cpp(coords, normals, year, day_start, day_end, day_step, minute_step, min_sun_angle, voxel_size, lat, lon, timezone));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vostokR_calculate_solar_potential_cpp", (DL_FUNC) &_vostokR_calculate_solar_potential_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_vostokR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
