# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_solar_potential_cpp <- function(coords, normals, year, day_start, day_end, day_step, minute_step, min_sun_angle, voxel_size, lat, lon, timezone) {
    .Call(`_vostokR_calculate_solar_potential_cpp`, coords, normals, year, day_start, day_end, day_step, minute_step, min_sun_angle, voxel_size, lat, lon, timezone)
}

