# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_vostokr_threads <- function(n_threads) {
    invisible(.Call(`_vostokR_set_vostokr_threads`, n_threads))
}

get_vostokr_threads <- function() {
    .Call(`_vostokR_get_vostokr_threads`)
}

get_actual_vostokr_threads <- function() {
    .Call(`_vostokR_get_actual_vostokr_threads`)
}

get_vostokr_max_threads <- function() {
    .Call(`_vostokR_get_vostokr_max_threads`)
}

clear_vostokr_caches <- function() {
    invisible(.Call(`_vostokR_clear_vostokr_caches`))
}

get_vostokr_performance_info <- function() {
    .Call(`_vostokR_get_vostokr_performance_info`)
}

calculate_solar_potential_cpp <- function(coords, normals, year, day_start, day_end, day_step, minute_step, min_sun_angle, voxel_size, lat, lon, timezone) {
    .Call(`_vostokR_calculate_solar_potential_cpp`, coords, normals, year, day_start, day_end, day_step, minute_step, min_sun_angle, voxel_size, lat, lon, timezone)
}

